Fix the nth case of broken symlinks in icons
In this case, labplot2.svg was pointing to a non-existent file
(/media/daten/git/breeze/icons/apps/48/labplot.svg).

This is the third time in a few days: *please* check for absolute
symlinks when adding files, as they make packaging breeze icons
impossible, as this error explains (taken from an openSUSE packaging
attempt):

ERROR: link target doesn't exist (neither in build root nor in installed
system): /usr/share/icons/breeze-dark/apps/48/labplot2.svg -&gt;
/media/daten/git/breeze/icons/apps/48/labplot.svg

CCMAIL: kainz.a@gmail.com

Commit 278071edd386a023a3005a35cdece843428094f0 in kde:breeze